/*
 * あくまでも例です
 */
loadExternalFile([
 {
  type:"css",
  list:["//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css","/~virus/lib/bootstrap/css/bootstrap.min.css"]
 },
 {
  type:"javascript",
  list:["//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js","/~virus/lib/jquery.js"]
 },
 {
  type:"javascript",
  list:["//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js","/~virus/lib/bootstrap/js/bootstrap.min.js"]
 },
 {
  type:"javascript",
  list:["./javascript/main.js"]
 },
]);
